# Generated by Django 3.0.7 on 2020-10-21 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='emailaddress',
            new_name='address',
        ),
    ]
