# Generated by Django 3.0.7 on 2020-10-28 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_auto_20201028_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='profile_pic',
        ),
    ]
