# Generated by Django 3.0.7 on 2020-10-05 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_remove_customer_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='months',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.Customer'),
        ),
    ]
