# Generated by Django 3.0.7 on 2020-10-26 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_auto_20201023_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='months',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
